### PR TITLE
More Logs

### PR DESCRIPTION
**Pull request by enriavil1**
Changed anchor logging lvl to debug from info to avoid spamming and losing error messages when stage fails.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
- "losing error messages when stage fails" - i never seen "stage headers fails" - what do you mean?
- Did we fix all "StageHeader suck" errors? 
- If you mean that some error happened, and after this "StageHeader suck" - then probably this anchor logs must be useful to explain - why it stuck? Maybe if on previous iteration we had error, and now "StageHeader suck" then maybe need show this error right in current anchor logs?

**Comment by enriavil1** [comment]
> * "losing error messages when stage fails" - i never seen "stage headers fails" - what do you mean?
> * Did we fix all "StageHeader suck" errors?
> * If you mean that some error happened, and after this "StageHeader suck" - then probably this anchor logs must be useful to explain - why it stuck? Maybe if on previous iteration we had error, and now "StageHeader suck" then maybe need show this error right in current anchor logs?

Not really stuck but we usually get a warning log (currently has happened in execution stage or interstate hashes), so what ends up happening is that users get spammed with anchor logs which leads them to losing the warning log that we need.

**Comment by AskAlexSharov** [comment]
I have feeling that it's "not enough" solution for "leads them to losing the warning log that we need.". 
User anyway may get much other logs (good peers, txpool, StageHeader, ...) and loose warn/error. 
- Maybe we need keep and print bad block num/hash sometime? 
- What is our usual recommendation when user come to us with bad block? "Please try to unwind 100 blocks?" Can erigon do it? If it has bad block and StageHeader doesn't move anywhere 15 min, then try unwind more? 
- Maybe we can print more debug info to make user's bug-report more useful than just: "I got stateRoot mistmatch error and then node stuck"?

**Comment by enriavil1** [comment]
> I have feeling that it's "not enough" solution for "leads them to losing the warning log that we need.". User anyway may get much other logs (good peers, txpool, StageHeader, ...) and loose warn/error.
> 
> * Maybe we need keep and print bad block num/hash sometime?
> * What is our usual recommendation when user come to us with bad block? "Please try to unwind 100 blocks?" Can erigon do it? If it has bad block and StageHeader doesn't move anywhere 15 min, then try unwind more?
> * Maybe we can print more debug info to make user's bug-report more useful than just: "I got stateRoot mistmatch error and then node stuck"?

@AskAlexSharov I have added a constant log of the latest block invalid block hash. I feel like the spamming of the anchor logs might be confusing to people, but I agree its better to show them than to not.

**Pull request closed without merging**
