### PR TITLE
txpool: Add a flag to disable TxPoolGossip

### PR DESCRIPTION
**Pull request by Boyuan-Chen**
This PR adds a new flag to TxPool that can disable the TxPoolGossip feature. This feature is designed for Optimistic Rollup. By disabling TxPoolGossip, the sequencer node can prevent MEV attacks. The default option is set to `false`, so it doesn't impact any existing functions.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
"sequencer node can prevent MEV attacks" - can you share more about it? 
other eth clients have this feature?

**Comment by AskAlexSharov** [comment]
@Boyuan-Chen ping

**Comment by Boyuan-Chen** [comment]
> "sequencer node can prevent MEV attacks" - can you share more about it? other eth clients have this feature?

No, this is for the Optimism's execution engine. The TX pool is disabled, so no one can see the pending txs.

**Comment by AskAlexSharov** [comment]
mmm... don't understand how to push changes in forked PR... created another PR with some changes:
https://github.com/ledgerwatch/erigon/pull/8800

**Comment by AskAlexSharov** [comment]
please review https://github.com/ledgerwatch/erigon/pull/8800

**Comment by Boyuan-Chen** [comment]
> please review #8800

Ok, thank you.

**Comment by AskAlexSharov** [comment]
closing this PR and merging https://github.com/ledgerwatch/erigon/pull/8800 
@Boyuan-Chen thank you.

**Pull request closed without merging**
