### PR TITLE
torrent-related goroutine leack

### PR DESCRIPTION
**Pull request by AskAlexSharov**
can't merge - because `torrent` lib dropped go1.19 support

### CODE REVIEW

**Comment by blxdyx** [comment]
May I know the expected timeline for this PR to be merged?

**Comment by AskAlexSharov** [comment]
need to fork torrent lib which does support 1.20 and backport the fix there.

**Comment by blxdyx** [comment]
Does it mean that it won’t be updated to go1.20?

**Comment by AskAlexSharov** [comment]
Erigon supports 1.19 and 1.20

**Pull request merged**
