### PR TITLE
config: avoid OOM in docker using cgroups v2 limit (#6646)

### PR DESCRIPTION
**Pull request by battlmonstr**
Tested on Debian 11 by:

    $ git revert HEAD
    $ make docker
    $ docker run --memory=8.8G <sha>

before the fix outputs:

    15.6 GB

after the fix outputs:

    8.8 GB

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
I love it. This topic didn't move for a year. Yes, some tons of deps (bindings to ebpf, systemd) but let's keep it - seems it will not hard to support.

**Comment by luarx** [comment]
Just to know more about this:
What want to fix this issue? Is it normal to still see OOM in docker after the relese that contains this?  🙏

**Comment by AskAlexSharov** [comment]
@luarx not normal. create another issue with version/hardware/logs.

**Comment by luarx** [comment]
Created https://github.com/ledgerwatch/erigon/issues/9645 🙏

**Pull request merged**
