### PR TITLE
Added serenity consensus engine

### PR DESCRIPTION
**Pull request by Giulio2002**
This PR just introduces the checks that Serenity does from the execution layer side. This is not the whole "merger"

### CODE REVIEW

**Comment by Giulio2002** [comment]
not sure why one check failed, seems like it just decided to stop

**Comment by Giulio2002** [comment]
Just tell me what you think, i need to add more to this

**Comment by Giulio2002** [comment]
Actually, on second thought, I don't know if we need this, i will close and in case reopen

**Comment by AskAlexSharov** [comment]
all good

**Comment by Giulio2002** [comment]
just kidding we need this

**Comment by Giulio2002** [comment]
mind if i merge?

**Pull request merged**
