### PR TITLE
Adding InititateValidatorExit

### PR DESCRIPTION
**Pull request by michaelneuder**
Spec: https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#initiate_validator_exit

Part of https://github.com/ledgerwatch/erigon/issues/5965

### CODE REVIEW

**Comment by Giulio2002** [comment]
Net test is broken, will rerun CI and see if it is isolated

**Comment by Giulio2002** [comment]
otherwise LGTM

**Comment by michaelneuder** [comment]
ya i am pretty sure that test is unrelated. let me try to get the CI to rerun.

**Comment by Giulio2002** [comment]
I think my latest PR caused some conflicts sorry about that

**Comment by Giulio2002** [comment]
should have merged this one first but slipped through my mind :)

**Comment by michaelneuder** [comment]
no worries! fixed the conflicts

**Pull request merged**
