### PR TITLE
Add transaction rlp encoder. Use it in DynamicFeeTransaction

### PR DESCRIPTION
**Pull request by Cript**
RLP decoder was added to reduce copy/paste in the `DecodeRLP` method of transactions.
For now, it is only used in *DynamicFeeTransaction*. I would like to know your opinion about this approach. If it is ok I will update other types of transactions.

Also, there are two approaches:
1. Send parameter to the function
```
err = decoder.Data(&tx.Data)
```
2. Return it from it
```
value, err := decoder.Value()
tx.Value = value
```

Both of these have one drawback: check error
```
if err != nil {
    return err
}
```

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Thank you. 
FYI: we have similar concept in erigon-lib: https://github.com/ledgerwatch/erigon-lib/blob/8d06531e4ed30edc74688634afcfc898e5291ff8/txpool/types.go#L44
But variant in erigon-lib now support only logic useful for txpool (historical hard-forks not supported). It is thread-unsafe, and created when app starts. 

Probably it make sense - also implement it in erigon-lib, because erigon-lib has better license. (You can extend existing class there, or create new one, also it’s ok to move some files to new packages inside erigon-lib if you will have cyclic-imports). 

what do you think?

**Comment by Cript** [comment]
Sounds good to move it to erigon-lib.
What I really would like to implement is completely remove the `DecodeRLP` method from the `Transactions`
Add `TransactionDecoder` interface, `TransactionRLPDecoder` struct (core/types/transaction_rlp_decoder.go from this PR) which will receive `rlp.Stream` and return the appropriate transaction. I guess decoding should be separated from transactions to avoid code duplication.
What do you think?

**Comment by AskAlexSharov** [comment]
I’m ok with your advise and erigon-lib’s transaction decoder does this thing (it accept pointer to transaction as an argument because it allow reduce allocations). 

Problem: you will not able to use rlp.Stream from erigon-lib because it’s not in erigon-lib(maybe can as some custom interface). Also you can’t return “types.*” because they are not in erigon-lib(maybe “golang aliases” can help here). But erigon-lib has own rlp primitives which work on top of raw bytes slice (see “rlp” package), and TxParseContext has 80% of transaction parsing functionality. 

So, I’m ok with what you doing - just don’t know what is “easy first step” here (if we wanna do it in erigon-lib).

**Comment by Cript** [comment]
I get it. Better to move rpl decoding to erigin-lib and try to use `TxParseContext` there.

**Comment by Cript** [comment]
This PR should be closed and rethought

**Comment by AskAlexSharov** [comment]
It's ok to leave "encoding" out of scope for now and focus only on moving "decoding".

**Pull request closed without merging**
