### PR TITLE
[BSC] support for Moran fork

### PR DESCRIPTION
**Pull request by 14MR**
This PR brings support for BSC Moran fork

### CODE REVIEW

**Comment by masayil** [comment]
@14MR hi   you forgot the bsc chapel testnet

**Comment by sjlee1125** [comment]
Does this commit cover chapel testnet?

**Comment by 14MR** [comment]
@sjlee1125 @masayil updated the chainspec

**Comment by tsutsu** [comment]
@14MR you're missing this part of the patch:

```diff
diff --git a/core/vm/evm.go b/core/vm/evm.go
index c671e5c3e..33d0fb5ad 100644
--- a/core/vm/evm.go
+++ b/core/vm/evm.go
@@ -45,6 +45,8 @@ type (
 func (evm *EVM) precompile(addr common.Address) (PrecompiledContract, bool) {
        var precompiles map[common.Address]PrecompiledContract
        switch {
+       case evm.chainRules.IsMoran:
+               precompiles = PrecompiledContractsIsMoran
        case evm.chainRules.IsNano:
                precompiles = PrecompiledContractsNano
        case evm.chainRules.IsBerlin:
```

**Comment by 14MR** [comment]
> @14MR you're missing this part of the patch:
> 
> ```diff
> diff --git a/core/vm/evm.go b/core/vm/evm.go
> index c671e5c3e..33d0fb5ad 100644
> --- a/core/vm/evm.go
> +++ b/core/vm/evm.go
> @@ -45,6 +45,8 @@ type (
>  func (evm *EVM) precompile(addr common.Address) (PrecompiledContract, bool) {
>         var precompiles map[common.Address]PrecompiledContract
>         switch {
> +       case evm.chainRules.IsMoran:
> +               precompiles = PrecompiledContractsIsMoran
>         case evm.chainRules.IsNano:
>                 precompiles = PrecompiledContractsNano
>         case evm.chainRules.IsBerlin:
> ```

Thank you, i also found a few missing parts in tests. Updated

**Pull request merged**
