### PR TITLE
fixed prune flag not working with htrc

### PR DESCRIPTION
**Pull request by enriavil1**
Solving issue #5115

### CODE REVIEW

**Comment by yperbasis** [comment]
Hmm. This does not fix Issue #5115 for me.

**Comment by enriavil1** [comment]
> Hmm. This does not fix Issue #5115 for me. 

What error message are you getting? The same one?

**Comment by yperbasis** [comment]
> What error message are you getting? The same one?

Yes, the same error.

**Comment by enriavil1** [comment]
> > What error message are you getting? The same one?
> 
> Yes, the same error.

Seems like the pruning is getting turned on at some point, so I am looking for that too and adding preventive measures.

**Pull request merged**
