### PR TITLE
Observer - P2P network crawler

### PR DESCRIPTION
**Pull request by battlmonstr**
Observer crawls the Ethereum network and collects information about the nodes.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
Need fix WIN build: that error means - some files were not closed properly (defer f.Close() missed somewhere).

**Comment by AskAlexSharov** [comment]
Then - can just merge and iterate by future PR’s.

**Comment by AlexeyAkhunov** [comment]
> Then - can just merge and iterate by future PR’s.

Better to fix now, because it will be failing in `devel` all the time. I have pushed the fix, hopefully it'll help

**Comment by battlmonstr** [comment]
@AlexeyAkhunov I didn't notice your fix, and force-pushed my own fix on top 😅

**Comment by AlexeyAkhunov** [comment]
> @AlexeyAkhunov I didn't notice your fix, and force-pushed my own fix on top 😅

no worries, as long as it is fixed, I am happy

**Pull request merged**
