### PR TITLE
add log-prefix to GasPriceOracle

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by battlmonstr** [comment]
@AskAlexSharov how about adding an API to create a child logger that appends an extra name, e.g.: `log := log.Sub("GasPriceOracle")` which logs with a `[<parent_name>.GasPriceOracle]` prefix?

**Review by battlmonstr — APPROVED** [review]

**Comment by AskAlexSharov** [comment]
@battlmonstr it exists: `logger.New("foo", "bar")`. See `TestLogContext`

**Comment by battlmonstr** [comment]
> @battlmonstr it exists: `logger.New("foo", "bar")`. See `TestLogContext`

is it possible to use it for this PR?

**Comment by AskAlexSharov** [comment]
ok

**Pull request merged**
