### PR TITLE
Add check to have pre-Homestead behavior on code store error

### LINKED ISSUE #2748: Pre-Homestead eth_call fails for code storage out-of-gas
#### System information

Erigon version: 2021.10.1-alpha

OS & Version: Linux Ubuntu 20.04.2 LTS

Commit hash: [e57c6d7](https://github.com/ledgerwatch/erigon/commit/e57c6d754627a9bb8634287309d889bdd2752931)

#### Expected behaviour
Response to eth_call API in mainnet is the same comparing:

RPCDaemon connected to Erigon Core
Silkrpc connected to Erigon Core
Etherscan (used as reference)

#### Actual behaviour
RPCDaemon+Erigon gives a different result from Etherscan and Sillkrpc+Erigon (which give the same result) executing eth_call for the following transaction: [0x41a8181184431f4277e3a0703a15d79450defd377e1e73ef040c00562b620389](https://etherscan.io/tx/0x41a8181184431f4277e3a0703a15d79450defd377e1e73ef040c00562b620389)

RPCDaemon: contract creation code storage out of gas
Silkrpc: OK
Etherscan: OK

#### Steps to reproduce the behaviour
Use the following command:
```
curl --silent -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "method": "eth_call", "params": [{"data": "0x60606040526000805460ff191690556002805462ffffff1916905560048054600160a060020a03191633179055610ec18061003a6000396000f3606060405236156100b95760e060020a60003504631f0ac3c881146100bb578063305075db146101bc57806335d13969146102e75780633cc86b80146103a75780633ffd80df146103ed5780634dc3141b146104315780636423db34146104775780636de00927146104d35780637281854d14610520578063755f99c21461054b578063769dc52314610574578063797fdd7b146105b8578063842bc37b146105e157806385a1c9501461062f578063e50d047314610657575b005b61050760043560243560443560ff8116600090815260016020526040812060020154819062ffffff16819011156106e65750604081206002015462ffffff16600019015b60008162ffffff1611156106f55760ff8316600090815260016020908152604080832062ffffff85168452600401909152902054600160a060020a0385811691161480156101af575084600160a060020a0316600160005060008560ff16815260200190815260200160002060005060040160005060008362ffffff16815260200190815260200160002060005060010160009054906101000a9004600160a060020a0316600160a060020a0316145b1561079c578091506106ed565b6100b9600454620186a09060009081908190819081908190600160a060020a039081163390911614156107a5575b60005460ff90811690861610156107a55760ff8516600090815260016020526040812090965093508592508291505b60025462ffffff90811690871610156107ae5762ffffff868116600090815260036020818152604080842054600160a060020a031684529188019052812054909116146102db576103e861ffff16846003016000506000600360005060008a62ffffff16815260200190815260200160002060009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060009054906101000a900462ffffff160362ffffff1683019250825081806001019250505b60019590950194610219565b6100b9600454600090600160a060020a03908116339091161415610a24575b60025462ffffff9081169082161015610a245762ffffff81166000908152600560205260409020546611c37937e0800090111561039f57604060008181205462ffffff84168252600360209081528383205460059091529251600160a060020a03939093169282818181858883f19350505050506000600560005060008362ffffff168152602001908152602001600020600050819055505b600101610306565b6100b9600435602435600454600160a060020a039081163390911614156103e957604051600160a060020a03821690600090849082818181858883f150505050505b5050565b6100b95b30600160a060020a03163160005b60005460ff9081169082161015610c3a5760ff81166000908152600160208190526040822001541415610c6e57610c8a565b6100b9600060006000600060006000600460009054906101000a9004600160a060020a0316600160a060020a031633600160a060020a03161415610e1757610c926103f1565b6100b9600454600090600160a060020a03908116339091161415610a24575b60005460ff9081169082161015610a245760ff81166000908152600160208190526040822060028101805462ffffff191690550155600101610496565b60ff600435166000908152600160209081526040808320600160a060020a0360243516845260030190915290205462ffffff165b6040805162ffffff929092168252519081900360200190f35b60ff600435166000908152600160208190526040909120015460408051918252519081900360200190f35b6100b9600435600454600160a060020a0390811633909116148015610a455750610a3a816105e8565b6106bc6004355b6000805b60005460ff90811690821610156106d35760ff811660009081526001602052604090205460e060020a028314156106de578091506106d8565b6100b9600435602435600454600090819032600160a060020a03908116911614610aea576106b6565b6105076004355b6000805b60025462ffffff9081169082161015610a275762ffffff8116600090815260036020526040902054600160a060020a0384811691161415610a32578091506106d8565b6100b960043560045433600160a060020a039081169116148015610a9b5750610a948161057b565b6100b960043560243560443560045460009033600160a060020a03908116911614156106b65760ff84168152600160209081526040808320600160a060020a038616845260038101909252909120805462ffffff191661ffff84161790555b50505050565b6040805160ff929092168252519081900360200190f35b60ff91505b50919050565b60010161057f565b62ffffff91505b509392505050565b60ff83166000908152600160209081526040808320838052600401909152902054600160a060020a03858116911614801561078e575084600160a060020a0316600160005060008560ff16815260200190815260200160002060005060040160005060006000815260200190815260200160002060005060010160009054906101000a9004600160a060020a0316600160a060020a0316145b156106e657600091506106ed565b600019016100ff565b50505050505050565b6103e8820261ffff1683111561091757506000945061ffff811682045b60025462ffffff908116908716101561090b5762ffffff868116600090815260036020818152604080842054600160a060020a0316845291880190529020546103e8911611156108ff578062ffffff166103e861ffff166103e861ffff16866003016000506000600360005060008c62ffffff16815260200190815260200160002060009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060009054906101000a900462ffffff160362ffffff1602046103e861ffff1601846003016000506000600360005060008a62ffffff16815260200190815260200160002060009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060006101000a81548162ffffff021916908302179055505b600195909501946107cb565b6103e8820261ffff1692505b600095505b60025462ffffff9081169087161015610a185762ffffff868116600090815260036020818152604080842054600160a060020a0316845291880190529020546103e891161115610a0c576103e861ffff16846003016000506000600360005060008a62ffffff16815260200190815260200160002060009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060009054906101000a900462ffffff160362ffffff16838802048460010160005054048702600560005060008862ffffff1681526020019081526020016000206000828282505401925050819055505b6001959095019461091c565b600194909401936101ea565b50565b62ffffff91506106d8565b6001016105ec565b62ffffff1662ffffff145b15610a24576002805462ffffff9081166000908152600360205260409020805473ffffffffffffffffffffffffffffffffffffffff191684179055815462ffffff198116911660010117905550565b60ff1660ff145b15610a24576000805460ff9081168252600160208190526040808420805460e060020a870463ffffffff199190911617905583548316845283208101839055825460ff19811692160117905550565b610af38361057b565b91508160ff1660ff1480610b165750610b0b336105e8565b62ffffff1662ffffff145b80610b305750610b25846105e8565b62ffffff1662ffffff145b15610b3a576106b6565b5060ff8116600090815260016020818152604080842092830180543401905533600160a060020a0316845260038301909152822054909162ffffff9091161415610b9457604060002080546103e862ffffff199091161790555b600160a060020a038416600090815260038201602052604081205462ffffff161415610bce576040600020805462ffffff19166103e81790555b60028101805462ffffff90811660009081526004840160205260408082206001908101805473ffffffffffffffffffffffffffffffffffffffff199081168b179091558554851684529190922080549190911633179055825462ffffff19811692160117905550505050565b6000805260016020527fa6eef7e35abe7026729641147f7915573c7e97b47efa546f5f6e3230263bcb4a8054830190555050565b60ff811660009081526001602081905260409091200154909103905b6001016103ff565b600094505b60005460ff9081169086161015610e175760ff8516600090815260016020526040812090965093508592505b600284015462ffffff9081169087161015610e1f5762ffffff868116600090815260048601602090815260408083208054600160a060020a03908116855292879052818420805461ffff811660010161ffff19919091161790555490911682528120546201000090049091161415610e0b578360030160005060008560040160005060008962ffffff16815260200190815260200160002060005060000160009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060009054906101000a900462ffffff168260008660040160005060008a62ffffff16815260200190815260200160002060005060000160009054906101000a9004600160a060020a0316600160a060020a0316815260200190815260200160002060005060000160026101000a81548162ffffff021916908302179055505b60019590950194610cc3565b505050505050565b600095505b600284015462ffffff9081169087161015610eb5575062ffffff858116600090815260048501602090815260408083208054600160a060020a0390811685528684528285205460018301549091168552600389019093529220805462ffffff19811690851661ffff848116600202166201000090940490951692909204939093011790915560019590950194610e24565b60019490940193610c9756", "from": "0x5149ebf29b2fc0206dd5a2b4bf8f429abf66f0f1",  "gas": "0xF4240", "gasPrice": "0xBA43B7400" }, "0x10750D"], "id": 1}' localhost:8545
```

#### Analysis
The transaction above, included in block [1078542](https://etherscan.io/block/1078542) mined before the Homestead hard fork (occurred at block 1150000), was successful even if produced an empty deployed [contract](https://etherscan.io/address/0x8fef965e5db6f7f1a165008499e8b7901cd766b2#code). One of the [Homestead HF changes](https://eips.ethereum.org/EIPS/eip-2) was exactly avoiding empty deployed contracts when contract creation does not have enough gas to pay for the final gas fee for adding the contract code to the state.
So it seems that a check is missing in EVM [create](https://github.com/ledgerwatch/erigon/blob/2e086bc188f697c8795e150f5ba2cc04c7bec9f1/core/vm/evm.go#L556) function to match the pre-Homestead behavior, which was buggy but nevertheless we should reproduce faithfully.

### PR DESCRIPTION
**Pull request by canepat**
Fixes #2748

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]

**Comment by AskAlexSharov** [comment]
@canepat geth has same error? https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L477

**Comment by canepat** [comment]
> @canepat geth has same error? https://github.com/ethereum/go-ethereum/blob/master/core/vm/evm.go#L477

It seems so but I don't have any Geth instance to give it a try

**Comment by canepat** [comment]
@AskAlexSharov can you please take a look at the linter error in Ubuntu CI? I have reproduced it locally installing `golangci-lint` but seems unrelated to this PR:
```
common/fdlimit/fdlimit_unix.go:16: File is not `gofmt`-ed with `-s` (gofmt)

p2p/netutil/toobig_notwindows.go:17: File is not `gofmt`-ed with `-s` (gofmt)
//+build !windows
crypto/blake2b/blake2bAVX2_amd64.go:4: File is not `gofmt`-ed with `-s` (gofmt)
```

**Comment by AskAlexSharov** [comment]
@canepat probably your local version of go is different

**Comment by AskAlexSharov** [comment]
You need format only your file. Linter i bit crazy :-)

**Pull request merged**
