### PR TITLE
 #2371: added saving Erigon version in database

### PR DESCRIPTION
**Pull request by e-danko**
## Updates
Added saving Erigon version in database when:
- database created
- stage==Finish && initialCycle==true

## Issue 
https://github.com/ledgerwatch/erigon/issues/2371

### CODE REVIEW

**Comment by AndreaLanfranchi** [comment]
What's the point of having this ?
And if erigon version changes ?

**Comment by e-danko** [comment]
> What's the point of having this ?
> And if erigon version changes ?

I'll add link to the issue: https://github.com/ledgerwatch/erigon/issues/2371

**Comment by AndreaLanfranchi** [comment]
Got it. Still don't understand what this (I mean having the version codebase which originally created the database persisted) could be useful for.

cc @AskAlexSharov hints ?

**Comment by AskAlexSharov** [comment]
If we will discover some bug with non-recoverable data corruption in future (we had bug where db migration can help only if apply within 2 weeks). We can write warning for user - that his db can’t be repaired anymore. 

About PR:
- “initialCycle” variable is also true - when node starts after downtime. 
- migrator doesn’t run when no migrations available. I think better do it in node.OpenDatabase method - which creating migrator.

**Comment by e-danko** [comment]
> * migrator doesn’t run when no migrations available. I think better do it in node.OpenDatabase method - which creating migrator.

i can add check if key already exists in both cases

**Comment by mandrigin** [comment]
@e-danko I think the issue with "migrator doesn’t run when no migrations available" is that you won't get your code ran in some cases. So hence moving to `node.OpenDatabase` is better.

**Comment by AskAlexSharov** [comment]
@AndreaLanfranchi example issue where first version (and even better - list of all code version): when user came with some "already fixed bug" - but it's hard to debug because likely people will not remember all versions of Erigon they used. Like here: https://github.com/ledgerwatch/erigon/issues/2633 - some piece of data missed, and looks like problem already fixed, but we don't exact reasons. Read through release notes - may help - if know which release notes need to read.

**Pull request merged**
