### PR TITLE
move stateless execution flag into vm config

### PR DESCRIPTION
**Pull request by sudeepdino008**

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Could you please refresh this based on the current `devel`?

**Comment by sudeepdino008** [comment]
> Could you please refresh this based on the current `devel`?

done

**Comment by sudeepdino008** [comment]
@AlexeyAkhunov you can check now.

**Comment by sudeepdino008** [comment]
@AlexeyAkhunov ping

**Comment by AlexeyAkhunov** [comment]
Oh sorry, I was still assuming it wasn't done, now there are more conflicts :( I will try to resolve them after the next release

**Comment by AlexeyAkhunov** [comment]
I have moved changes into this PR where I resolved the conflicts. Thanks a lot! https://github.com/ledgerwatch/erigon/pull/5710

**Pull request closed without merging**
