### PR TITLE
fix typo in external flag

### PR DESCRIPTION
**Pull request by racytech**

### CODE REVIEW

**Review by wmitsuda — CHANGES_REQUESTED** [review]
actually, it should be `externalcl` according to the error log

**Comment by wmitsuda** [comment]
@racytech I was going to just submit the PR, but saw you were first :)

**Comment by wmitsuda** [comment]
logs: `Caplin is enabled, so the engine API cannot be used. for external CL use --externalcl`

**Comment by racytech** [comment]
@wmitsuda  will do that

**Pull request closed without merging**
