### PR TITLE
diagnostics: add packet loss and cacheServerList for speedtest

### PR DESCRIPTION
**Pull request by r3inbowari**

### CODE REVIEW

**Review by dvovk — APPROVED** [review]

**Comment by AskAlexSharov** [comment]
@r3inbowari why do we need cached client object?

**Comment by r3inbowari** [comment]
> @r3inbowari why do we need cached client object?

Fallback to the last cache when the server fails to fetch.

**Comment by AskAlexSharov** [comment]
@r3inbowari ah, it's flipped go's pattern of error handling. my bran did know `if err == nil {` exists in this world:
```
	serverList, err := speedtestClient.FetchServers()
	// Ensure that the server list can rolled back to the previous cache.
	if err == nil {
		cacheServerList = serverList
	}
        targets, _ := cacheServerList.FindServer([]int{})
```
so, we ignore error. i see...
then it's `nil` in first run. and if first call will return error - we will get `nil-ptr` panic. probably need add nil-check.

**Comment by r3inbowari** [comment]
> if first call will return error - we will get `nil-ptr` panic. probably need add nil-check.

Hi, @AskAlexSharov, nil-checks are always good. In the original `FetchServers` in speedtest-go, an error and empty array will be returned. I haven't modified this part of the code.

**Pull request merged**
