### PR TITLE
Adding a new stage for snapshots download and creation

### PR DESCRIPTION
**Pull request by leonardchinonso**
Creating a special stage for snapshots by moving all snapshots download related code from stage_headers.go into its own file. This way we have a single stage for snapshots separate from headers aka cleaning up.
solving issue: #5223

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]
looks good. Let's test it a bit before merge. 

- In next PR need move `retireBlocksInSingleBackgroundThread` from stage_sender to stage_snapshots.prune

- optionally can add some comments/docs for stage: that it calling Downloader service and it waiting for snapshots to be 100% downloaded, and it set other stages progress depends how much snapshots are available.

**Comment by enriavil1** [comment]
> looks good. Let's test it a bit before merge.
> 
> * In next PR need move `retireBlocksInSingleBackgroundThread` from stage_sender to stage_snapshots.prune
> * optionally can add some comments/docs for stage: that it calling Downloader service and it waiting for snapshots to be 100% downloaded, and it set other stages progress depends how much snapshots are available.

I was able to sync goerli fully yesterday using the branch. Next PR we can do the other sections. @leonardchinonso is adding a high level explanation on how it work into the ReadMe.

**Comment by AskAlexSharov** [comment]
Merge devel plz

**Comment by enriavil1** [comment]
> Merge devel plz

Done

**Pull request merged**
