### PR TITLE
Decoding incarnation implemented

### PR DESCRIPTION
**Pull request by enriavil1**

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
In this PR all is good. 
But this PR changing state-related functionality and we have some heavy tests which are not part of CI - and I advise you to run it and check that change doesn't break things.

I talking about next command: 
```
go run -trimpath ./cmd/integration state_stages --datadir=<datadir> --unwind=1000 --integrity.fast=false
go run -trimpath ./cmd/integration state_stages --datadir=<datadir> --unwind=5 --unwind.every=17 --integrity.fast=false
```
This command will run different form of real chain re-orgs. StageInterhashes (which is based on StageHashState) does calculate hash of all state and compare it with `header.Root`. If even 1 byte of state will change - this check will catch it.

**Comment by AskAlexSharov** [comment]
Ok, no reply ;-)

**Comment by enriavil1** [comment]
> Ok, no reply ;-)

I am sorry, I didn't see the message. I'll check it out today right away.

**Comment by enriavil1** [comment]
> Ok, no reply ;-)

Sorry with the lateness. I have run both commands and both of them ran without error or warning. Thank you for your help

**Pull request merged**
