### PR TITLE
Makefile (#3779): pass docker build arguments (stable)

### PR DESCRIPTION
**Pull request by battlmonstr**
Dockerfile requires some --build-arg options.
Fix "docker" target to pass them.
Fix GIT_TAG to reflect the most recent tag related to HEAD, instead of an unrelated most recent tag.
Use it as the image VERSION.

Image tags need to be passed explicitly if needed:

    DOCKER_FLAGS='-t erigon:latest' make docker

### CODE REVIEW

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]
I see next output on mac: 
```
git checkout devel
git pull --tags
git describe --tags '--match=v*'
v2021.10.03-1137-g2da927b74
```
so, it shows oldest tag, not newest

**Comment by battlmonstr** [comment]
> I see next output on mac:
> 
> ```
> git checkout devel
> git pull --tags
> git describe --tags '--match=v*'
> v2021.10.03-1137-g2da927b74
> ```
> 
> so, it shows oldest tag, not newest

I believe that v2021.10.03 is the most recent tag on the devel branch, before devel was forked from master. As far as I understand, version v2021.10.03 was released, then devel was forked, then after 1137 commits we have commit g2da927b74 on devel, and there are no other tags on commits in between.
If you want to see a newer devel version, need to tag some commit on the devel branch.

**Comment by battlmonstr** [comment]
As far as I understand we're not releasing from devel, but Alexey is maintaining some alpha branches where he cherry-picks devel commits, and tags them there.

One way to avoid seeing the stable tag v2021.10.03 on devel all the time, could be to mark some commit as `vDEV`, or maybe `v2021.XX.YY-dev`.

**Comment by AskAlexSharov** [comment]
I like your last idea. feel free to do something make sense for you.

**Comment by battlmonstr** [comment]
@AskAlexSharov this PR is a backport for the stable branch. A way to verify this would be to merge this to stable, make a new stable version tag/release (the previous one was v2022.04.02). Wait for the docker build to appear at https://hub.docker.com/repository/docker/thorax/erigon/builds , run this container with /usr/local/bin/erigon and see what it outputs.

One problem I see now though, is that the Docker Hub build is not using `make docker`, but uses Dockerfile as a starting point. It means that the variables BUILD_DATE, VCS_REF, VERSION are gonna be empty there. We need to change it so that the variables are populated by the shell/make script from the build stage instead of passing them as ARGs.

**Review by AskAlexSharov — APPROVED** [review]

**Pull request merged**
