### PR TITLE
Remove deduplication in NodeInfo response

### PR DESCRIPTION
**Pull request by dsavelev**
https://github.com/ledgerwatch/erigon/pull/3046#issuecomment-983100123

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
adding "beta" because the initial PR had the same thing

**Comment by AlexeyAkhunov** [comment]
Thanks. Does `go mod tidy` remove anything here?

**Comment by AlexeyAkhunov** [comment]
> adding "beta" because the initial PR had the same thing

Thank you, we will include this into the next beta release I think

**Comment by dsavelev** [comment]
> Thanks. Does `go mod tidy` remove anything here?

Oh, right, forgot about that.

**Pull request merged**
