### PR TITLE
Missed RPC calls implemented in BSC geth

### PR DESCRIPTION
**Pull request by gladcow**
BSC geth contains several RPC API calls under 'eth' namespace which are missed in Erigon. That means some issues are possible when you are trying to substitute BSC geth instance with Erigon instance, some services that use this API can be broken.

Full list of this RPC calls:

    eth_getDiffAccountsWithScope
    eth_getHeaderByHash
    eth_getDiffAccounts
    eth_getVerifyResult
    eth_health
    eth_getHeaderByNumber
    eth_getTransactionsByBlockNumber
    eth_resend
    eth_fillTransaction
    eth_getTransactionDataAndReceipt
    eth_getTransactionReceiptsByBlockNumber
    eth_pendingTransactions
    eth_getHashrate
    eth_etherbase
    eth_subscribeSyncStatus
    eth_getFilterLogs

Some of this calls are not implemented in original geth too, so this API set is optional, it is available only if user adds bsc entity to -http.api parameter (i.e. `./rpcdaemon --datadir=/dev  --private.api.addr=localhost:9090 --http.api=eth,erigon,web3,net,debug,trace,parity,txpool,bsc`). But user can call them in 'eth' namespace in spite of the bsc name for this API module (i.e. python code: `response = requests.post('http://localhost:18545', json=request("eth_getTransactionReceiptsByBlockNumber", params=[1]))`).

Not all of this functions are implemented here (for example, functions related to account usage like `eth_resend` or `eth_pendingTransactions`, etc.) but I have added their declaration to have the full list of missed implementation for the future improvements.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
thank you
we need some internal discussions about it

**Comment by AlexeyAkhunov** [comment]
So far we are not certain whether the support for BSC will stay beyond 1st of April, as described here: https://erigon.substack.com/p/future-of-the-support-of-bnb-smart

if it stays, then definitely we will accept this PR. Thanks for helping!

**Comment by AlexeyAkhunov** [comment]
Thank you! Unfortunately, the BSC support has been removed. node real will now be supporting a fork of Erigon for BSC: https://github.com/node-real/bsc-erigon

**Comment by gladcow** [comment]
Thank you for new fork info.

**Pull request closed without merging**
