### PR TITLE
change: port js tracer changes

### PR DESCRIPTION
**Pull request by fdymylja**
closes: #2447

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Thank you! I am assuming this is still work in progress?

**Review by fdymylja — COMMENTED** [review]
Question 1:
There are some tracers, specifically:
- cmd/rpcdaemon/commands/trace_adhoc.go
- cmd/state/commands/opcode_tracer.go
- eth/calltracer/calltracer.go

which are not compatible anymore with the new tracer interface, as some information is now missing (depth, code).


So I am not sure which steps to take for those, should this information be propagated (note that in the changes made in go-ethereum, `tracer.CaptureStart` is called only if depth is 0) somewhere? Or should the affected tracers' logic be changed?

I've marked every part of code affected with a `TODO(fdymylja):`

**Comment by fdymylja** [comment]
Question 2:

In porting https://github.com/ethereum/go-ethereum/commit/9d10856e84e884936c2390360e60e9ebca6d7a34

I've noticed (almost) every API affected is fully commented out in erigon, so I am not sure if those changes should be reflected somewhere else in erigon that I am not aware of.

**Comment by AskAlexSharov** [comment]
@fdymylja all api's are in `./cmd/rpcdaemon/commands`

**Comment by AlexeyAkhunov** [comment]
> Question 1: There are some tracers, specifically:
> 
> * cmd/rpcdaemon/commands/trace_adhoc.go

We only really care about the one above, because it is used to provide compatibility with `trace_` method of OpenEthereum. Other things (like opcode tracer) can be removed if they are not compatible.

**Comment by fdymylja** [comment]
> > Question 1: There are some tracers, specifically:
> > 
> > * cmd/rpcdaemon/commands/trace_adhoc.go
> 
> We only really care about the one above, because it is used to provide compatibility with `trace_` method of OpenEthereum. 

Thank you @AlexeyAkhunov and @AskAlexSharov!

Ok, I am wondering what would be the preferred approach in this case, since the new go-ethereum tracer API does not propagate the following information: depth, precompile and calltype. 

Should I modify the tracer interface to propagate the information required in trace_adhoc, or should I remove the parts of trace_adhoc which depend on those arguments?

Ref on interface breakage: https://github.com/ethereum/go-ethereum/commit/0fda25e471aa0e061396050c3d5e59fbaaf1e7b0#diff-b113b746a179a50a510cf20607b72357517c03434fe64479e90543cbde35c600L110

**Comment by AlexeyAkhunov** [comment]
> Should I modify the tracer interface to propagate the information required in trace_adhoc, or should I remove the parts of trace_adhoc which depend on those arguments?

Ideally we would like to modify tracer interface to propane the information required in trace_adhoc. We have a lot of users who depend on this functionality since they switched from OpenEthereum. Thank you for your work!

**Pull request closed without merging**
