### PR TITLE
Speed up docker image build by use layer cache

### PR DESCRIPTION
**Pull request by eval-exec**
Docker image build will use cached layers, since`go.mod` and `go.sum` won't changed very often, so we can add `RUN go mod download` early in `Dockerfile`.

# Reference:
https://cloud.google.com/architecture/best-practices-for-building-containers#optimize-for-the-docker-build-cache

### CODE REVIEW

**Review by AskAlexSharov — CHANGES_REQUESTED** [review]
`WORKDIR /app` is on top - means any change in app code will make all next layers cache invalid. 
same about erigon deps - because it's line before "apt instal", then you will need re-install gcc on any change in erigon deps. 
please re-arrange lines by change frequency (of it's content)

**Comment by eval-exec** [comment]
> `WORKDIR /app` is on top - means any change in app code will make all next layers cache invalid. same about erigon deps - because it's line before "apt instal", then you will need re-install gcc on any change in erigon deps. please re-arrange lines by change (of it's content) frequency

I think "--no-cache" on `RUN` phase of "apk install" is not necessary. So I rearranged `Dockerfile`, and removed `--no-cache`.

**Comment by eval-exec** [comment]
` git commit --amend --no-edit` and trigger githuhb action CI.

**Comment by AskAlexSharov** [comment]
“WORKDIR /app” - i miss-read it initially as “ADD . .” :-) 
Great

**Review by AskAlexSharov — APPROVED** [review]

**Pull request merged**
