### PR TITLE
feat(k8s): base with google-kubernetes-engine overlay example

### PR DESCRIPTION
**Pull request by beejiujitsu**
re: https://discord.com/channels/687972960811745322/738982866670714901/1041381487754354689

Introduces a more modular base with a google-kubernetes-engine overlay example.

### CODE REVIEW

**Review by AskAlexSharov — APPROVED** [review]

**Comment by beejiujitsu** [comment]
Thank you @AskAlexSharov !

**Comment by umeshtyagitvz** [comment]
Loadbalancer is not ensuring for UDP service

**Comment by beejiujitsu** [comment]
> Loadbalancer is not ensuring for UDP service

Hi @umeshtyagitvz, this isn't the place to file issues.

Can you create a new issue using https://github.com/ledgerwatch/erigon/issues/new/choose, what you're seeing vs what you expect for the bug, and tag me in a comment?

**Comment by AskAlexSharov** [comment]
@beejiujitsu hi. can you help to update example with following recommendations:
- Service account tokens should not be mounted in pods 
- Memory limits should be enforced
- CPU limits should be enforced

**Comment by beejiujitsu** [comment]
> @beejiujitsu hi. can you help to update example with following recommendations:
> 
> * Service account tokens should not be mounted in pods
> * Memory limits should be enforced
> * CPU limits should be enforced

Maybe.

I left the company that I originally wrote this for, and have since moved on from working in the crypto space.

Can you open an issue https://github.com/erigontech/erigon/issues/new/choose and tag/mention me on it with details?

**Pull request merged**
