### PR TITLE
Full BSC support with validator mode

### PR DESCRIPTION
**Pull request by dmitry123**
This PR includes BSC support for Erigon blockchain node implementation:

- Migrated Parlia consensus engine
- Added genesis block generation and peer discovery settings for bsc, chapel and rialto
- Fixed bug with modifying mutable balance object in inter block state
- Full support of all BSC forks
- Validator mode for Parlia consensus
- BSC and Parlia under flags
- Fully compatible with ETH mode

This is a copy of this PR but from this remote's branch: https://github.com/ledgerwatch/erigon/pull/3144

### CODE REVIEW

**Comment by h1ght1me** [comment]
Trying to sync Chapel testnet and sometimes getting this error in logs:

`Jan 13 13:20:50 erigon-bsc-develop erigon[11542]: [EROR] [01-13|13:20:50.331] Staged Sync                              error="runtime error: index out of range [46] with length 46, trace: [stageloop.go:120 panic.go:1047 panic.go:90 header_data_struct.go:117 heap.go:93 heap.go:86 header_algos.go:593 stage_headers.go:423 stage_headers.go:121 default_stages.go:20 sync.go:318 sync.go:235 stageloop.go:154 stageloop.go:58 asm_amd64.s:1581]"`

`Build info                               git_branch=bsc git_tag=v2022.01.01 git_commit=78bdc3b70202fdfc62637bbde8a081fb1bfbd734
`

**Comment by AlexeyAkhunov** [comment]
> Trying to sync Chapel testnet and sometimes getting this error in logs:
> 
> `[EROR] [01-13|13:20:50.331] Staged Sync error="runtime error: index out of range [46] with length 46, trace: [stageloop.go:120 panic.go:1047 panic.go:90 header_data_struct.go:117 heap.go:93 heap.go:86 header_algos.go:593 stage_headers.go:423 stage_headers.go:121 default_stages.go:20 sync.go:318 sync.go:235 stageloop.go:154 stageloop.go:58 asm_amd64.s:1581]"`
> 
> `Build info git_branch=bsc git_tag=v2022.01.01 git_commit=78bdc3b70202fdfc62637bbde8a081fb1bfbd734`

Thanks for reporting, I will add fix for that too

**Comment by AskAlexSharov** [comment]
Similar error here: https://github.com/ledgerwatch/erigon/issues/3258

**Comment by dmitry123** [comment]
@AskAlexSharov Why you've removed map size for chaindata database?

https://github.com/ledgerwatch/erigon/pull/3233/commits/900aef2ced7a2128b0f6d1eab830ddeac40b6764#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618L525

**Comment by AlexeyAkhunov** [comment]
> @AskAlexSharov Why you've removed map size for chaindata database?
> 
> [900aef2#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618L525](https://github.com/ledgerwatch/erigon/commit/900aef2ced7a2128b0f6d1eab830ddeac40b6764#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618L525)

We need to think about/discuss it separately. As we are having an issue with 4Tb size anyway. I am not against this change, but I would like to bring it in separately, because it may affect not just BSC

**Pull request merged**
