### PR TITLE
#2119 - implemented trace_filter intersection mode for 

### PR DESCRIPTION
**Pull request by awskii**
Implemented intersection mode for Trace API Filter call. 
I'm not sure I used correct way to generate blocks for testing, please correct me if i'm wrong.

### CODE REVIEW

**Comment by mandrigin** [comment]
@awskii some comments

```
1. Instead err != ethdb.ErrKeyNotFound need use !errors.Is
2. in default section no check for err != ethdb.ErrKeyNotFound
everything else looks good to me
```

**Comment by awskii** [comment]
> @awskii some comments
> 
> ```
> 1. Instead err != ethdb.ErrKeyNotFound need use !errors.Is
> 2. in default section no check for err != ethdb.ErrKeyNotFound
> everything else looks good to me
> ```

Done, 
@AskAlexSharov, could you please check PR?

**Comment by AskAlexSharov** [comment]
run 
```
make lintci-deps
make lint
```

**Comment by AlexeyAkhunov** [comment]
Sorry for the delay, I have just reviewed it to decide whether to put it in `stable`, and it seems to me this does not perform what it is supposed to do. The intersection needs to happen not on the level of picking which addresses to use, but on the level of operating with bitmaps. In the union mode, the resulting bitmap looks like this:
```
bitmap(from_1) | bitmap(from_2) | .... | bitmap(to_1) | bitmap(to_2)
```

in the intersection mode, the resulting bitmap should look like:
```
(bitmap(from_1) | bitmap(from_2) | ... ) & (bitmap(to_1) | bitmap(to_2) | ... )
```

i.e. intersection happens where `&` sign is. The selection of set of bitmaps to retrieve from the database does not change

**Pull request merged**
