### PR TITLE
Implements net_peerCount RPC call for internal sentries

### PR DESCRIPTION
**Pull request by jonasbostoen**
This PR implements the `net_peerCount` RPC call for internal sentries.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
We already have option to run sentries separately `--sentry.api.addr` - then Erigon have no p2pServer.

**Comment by AlexeyAkhunov** [comment]
As discussed on Discord, more extensive changes are needed (to have a function in p2psentry to return info necessary for `admin_peers`, and aggregate and deduplicate it on the backend

**Comment by jonasbostoen** [comment]
@AlexeyAkhunov, can we split that into 2 different PRs? I can first work on implementing `net_peerCount` and `admin_peers` for internal sentries only, and then create a different PR for external sentries. That way we manage the scope a little bit. What do you think?

**Comment by AlexeyAkhunov** [comment]
> @AlexeyAkhunov, can we split that into 2 different PRs? I can first work on implementing `net_peerCount` and `admin_peers` for internal sentries only, and then create a different PR for external sentries. That way we manage the scope a little bit. What do you think?

Yes, that makes sense. So currently for external sentries it will return 0, right? That's ok for now

**Comment by jonasbostoen** [comment]
> Yes, that makes sense. So currently for external sentries it will return 0, right? That's ok for now
Yes. I will start working on internal `admin_peers` this weekend

**Comment by AlexeyAkhunov** [comment]
Ok, thank you! We can merge this, but we need to make corresponding PR in the `interfaces` repo so that the two repos are in sync

**Comment by AlexeyAkhunov** [comment]
Also, the protocol Minor version needs to be bumped in the file `ethdb/remote/remotedbserver/ethbackend.go`

**Pull request merged**
