### PR TITLE
rpc: 1559 in call and tracing

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by perama-v** [comment]
I did some testing at commit hash `243f66d ` looking at RPC calls to trace_transaction at the fork block `5062605` for Goerli. I'm not sure if this is useful for this particular PR, so please ignore if it is unrelated.

Using, TrueBlocks I called `chifra blocks -t 5062605` to get all the transactions in the fork block with `-t` to get traces. With verbose logging in TruBlocks, I exposed the following RPC errors:

```
curl -s --data '{"method":"trace_transaction","params":["0x0b08bbe52e24633c2c37ff8a76db9099b25b57d849ecc4816e5289508b0564d6"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
result:
--["error":"code":-32000]--
--["message":"method handler crashed"]--
```
and
```
curl -s --data '{"method":"trace_transaction","params":["0x638cf1e54977513b75196127a9633080b23c108ef03645805fd97ac971ad9ea1"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
result:
--["error":"code":-32000]--
--["message":"method handler crashed"]--
```
Calls to the blocks prior to the fork (`chifra blocks -t 5062604` and earlier) seem to be passing, and calls at and after the fork all return `method handler crashed` (manual testing of ~20 blocks). 

This behaviour is replicated on the `devel` branch. I tested on this branch with `git fetch`, then `git switch 1559_rpc_call_and_tracing` then `make erigon` and `make rpcdaemon`.

**Comment by AskAlexSharov** [comment]
@perama-v , thank you, it was related. Fixed in this branch.

**Comment by perama-v** [comment]
Great to hear. I pulled `devel` and ran the test again:

```
--------------------------------------------------
curl -s --data '{"method":"trace_transaction","params":["0x0b08bbe52e24633c2c37ff8a76db9099b25b57d849ecc4816e5289508b0564d6"],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
result:
--["error":"code":-32000]--
--["message":"first run for txIndex 0 error: fee cap less than block base fee: address 0xF19a20E7d221031c996f7E1a47Ed29D82108d2e4]--
--[feeCap: 0 baseFee: 1000000000"]--
earlyAbort: 0
curlID: 59
earlyAbort: 0
curlID: 61
--------------------------------------------------
```
This behaviour is slightly different now, but still occurs and after the Goerli fork block, but not before.

**Comment by AskAlexSharov** [comment]
@perama-v , I tested your tx and it works on goerli. Please check that you re-build and re-started Erigon and Rpcdaemon

**Comment by perama-v** [comment]
My apologies, I neglected to `make rpcdaemon`. I have verified that the behaviour is normal around the fork block.

Sorry!

**Comment by AskAlexSharov** [comment]
@perama-v , very nice.

**Pull request merged**
