### PR TITLE
Revert to simple polling wait

### PR DESCRIPTION
**Pull request by yperbasis**
Unfortunately PR #6763 breaks a few Hive tests, for example "Invalid Ancestor Chain Sync, Invalid StateRoot, Invalid P9". Thus reverting to the simpler old logic, but with the maximum wait kept as 1 sec.

### CODE REVIEW

**Comment by hexoscott** [comment]
Shame to throw the initial effort away for this code.  I didn't anticipate this trace issue I'm looking at taking so long, otherwise would have got to this sooner.  Could we wait another day and I'll see what I can find this evening/tomorrow before we revert?

**Comment by hexoscott** [comment]
Think I've sorted this, a silly mistake on my behalf.  Just running through the full hive suite now.  Will push a PR tomorrow morning if all looks good.

**Comment by AskAlexSharov** [comment]
Can it be related to https://github.com/ledgerwatch/erigon/issues/6807#issuecomment-1429005653 ?

**Comment by hexoscott** [comment]
> Can it be related to [#6807 (comment)](https://github.com/ledgerwatch/erigon/issues/6807#issuecomment-1429005653) ?

I'm not sure it's related, there's no mention of the stageLoopBusy call in those logs.  Can't rule it out though.  Be worth a try once the fix here is merged.  Hive should finish shortly so will find out (computer went to sleep overnight).

**Comment by hexoscott** [comment]
Created #6871 as an alternative

**Comment by yperbasis** [comment]
Closing in favour of PR #6871.

**Pull request closed without merging**
