### PR TITLE
Raise the limit of debug_accountRange to 8192 (if storage not requested)

### PR DESCRIPTION
**Pull request by wtdcode**
`debug_accountRange` is one of the cool rpc methods erigon provides. However, the hardcoded limit 256 makes it supper inefficient. In my personal benchmark, raising the limit to 8192 could boost the indexing process 3-4x faster and thus this PR raises the default limit.

I could understand the security consideration of the DDoS attack on this parameter. But it's an RPC method under the `debug` namespace, which is not common for external usage, and both limits impose similar database pressure. Therefore, it should be mostly safe to raise the limit to a moderate value.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
@wtdcode what does `indexing process` do?

**Comment by wtdcode** [comment]
> @wtdcode what does `indexing process` do?

Iterate the database to get all existing accounts.

**Comment by wtdcode** [comment]
> @wtdcode with storage?

No, plain account addreses.

**Comment by AskAlexSharov** [comment]
i think main problem of `debug_accountRange` - it doesn't limit amount of storage keys (including all storage if request). 
@wtdcode can we have 2 constants? one for `excludeStorage=true` another `excludeStorage=false`?

**Comment by wtdcode** [comment]
> i think main problem of `debug_accountRange` - it doesn't limit amount of storage keys (including all storage if request). @wtdcode can we have 2 constants? one for `excludeStorage=true` another `excludeStorage=false`?

Make sense, let me add the constants.

**Comment by wtdcode** [comment]
Done

**Review by AskAlexSharov — APPROVED** [review]

**Comment by wtdcode** [comment]
@AskAlexSharov Any blocker?

**Comment by AskAlexSharov** [comment]
CI is red because of https://github.com/ledgerwatch/erigon/pull/10774

**Pull request merged**
