### PR TITLE
Header downloader monitor for diagnostics system

### PR DESCRIPTION
**Pull request by anshulforyou**
## What's this PR about?

- Added states to be sent to diagnostics system for header downloader monitor
- Added the code for sending the states through the tunnel
- Code added for updating the states in the header_algos.go file

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
can run CI locally:
```
make lintci-deps
make lint
make test
```

**Comment by anshulforyou** [comment]
> can run CI locally:
> 
> ```
> make lintci-deps
> make lint
> make test
> ```

Somehow all the tests are passing locally. I am on a mac system. I am not sure why they are failing on windows and ubuntu.

**Comment by AskAlexSharov** [comment]
no, seems you didn't merge devel. I just did. let's see on CI.

**Comment by AskAlexSharov** [comment]
@anshulforyou i granted you permission to create branches in erigon's repo - so you don't need fork anymore.

**Comment by anshulforyou** [comment]
> @anshulforyou i granted you permission to create branches in erigon's repo - so you don't need fork anymore.

Got it, thanks for inviting me!

**Pull request merged**
