### PR TITLE
fixing bugs in the function GetBlockByTimeStamp

### PR DESCRIPTION
**Pull request by AleksanderAvila**
#6408 
Sometimes the number was close but too high. To solve this problem I moved backwards in order to find a closer block with the requested time stamp.

### CODE REVIEW

**Comment by enriavil1** [comment]
I find that here might be another problem. When getting headerByNumber through blockreader I am not able to get anything below block number 15820999. Anything lower I get nil which might be the second problem with #6408

**Review by AskAlexSharov — APPROVED** [review]
merge devel pls

**Comment by AskAlexSharov** [comment]
FYI: @enriavil1  I think you have permissions to create branches in Erigon repo.

**Comment by enriavil1** [comment]
> FYI: @enriavil1 I think you have permissions to create branches in Erigon repo.

I let my brother solve it so he can start contributing to erigon. I do have permission though thank you!

**Comment by AskAlexSharov** [comment]
1. One more time merge devel plz
2. Seems you committed tests submodule not by intention

**Comment by AlexeyAkhunov** [comment]
It has changes `tests` data, perhaps accidentally, please fix or revert

**Pull request merged**
