### PR TITLE
bugfix: Change trace_adhoc to use next-block gas prices

### PR DESCRIPTION
**Pull request by imagine-eth**
Ad-hoc traces are generally used to simulate the result of executing transactions on top of the current block (i.e. on a new block). Right now, the base gas fee used is that of the parent rather than that of the new block in which the new traced transaction might appear. This change should fix that.

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
@AlexeyAkhunov , do you have chance to test it against geth compatibility?

**Comment by AlexeyAkhunov** [comment]
Yes, I can test it against OE a bit later today I think

**Comment by Yggdrasill04** [comment]
It seems that this code `blockCtx.baseFee = baseFee` is not only used to judge whether the trace target baseFee is qualified, but also involves the change of balance. I am skeptical about this.

**Comment by Yggdrasill04** [comment]
And currently,  the trace module use the highest block. Changing this baseFee alone seems a bit contrary to the whole trace module. The most ideal way is to implement pendingTrace which use the data of the next block to trace on the basis of the highest block.

**Comment by AlexeyAkhunov** [comment]
Looks like it does not build, we do not have `consensus/misc/eip1559` package, the import should be for `consensus/misc`

**Comment by AskAlexSharov** [comment]
Or need copy ‘ consensus/misc/eip1559’ from geth if they have it

**Pull request closed without merging**
