### PR TITLE
Go 21 support

### PR DESCRIPTION
**Pull request by AskAlexSharov**

### CODE REVIEW

**Comment by AskAlexSharov** [comment]
https://github.com/libp2p/go-libp2p/issues/2428#issuecomment-1681777427

**Comment by AskAlexSharov** [comment]
blocked by https://github.com/ledgerwatch/erigon/issues/8078

**Comment by Giulio2002** [comment]
I can do it, may I yolo

**Comment by AskAlexSharov** [comment]
@Giulio2002 help for CI plz-plz.

**Pull request closed without merging**
