### PR TITLE
Verify PoS headers before inserting them into DB

### PR DESCRIPTION
**Pull request by yperbasis**
Also in this PR:
- Total difficulty stage merged into headers stage
- Support errors in `ExecutionStatus`
- `useExternalTx` boilerplate in `HeadersPOS`
- `latestValidHash` must be nil when status is SYNCING (per [Engine API](https://github.com/ethereum/execution-apis/blob/v1.0.0-alpha.5/src/engine/specification.md#response))
- Use `fixCanonicalChain` instead of `canonicalHeadersCollector`
- Don't gossip PoS headers

### CODE REVIEW

**Comment by Giulio2002** [comment]
Wait how did you merge totalDifficulty and stage headers if stage headers is backwards, we dont know previous block's total difficulty so how would we know what previous sum is?

**Comment by yperbasis** [comment]
> Wait how did you merge totalDifficulty and stage headers if stage headers is backwards, we dont know previous block's total difficulty so how would we know what previous sum is?

We download the headers in the backward direction until we hit a previously downloaded header. But then, during the ETL load, we save them into the DB in the forward direction, so we know the previous total difficulty.

**Comment by Giulio2002** [comment]
> 
> We download the headers in the backward direction until we hit a previously downloaded header. But then, during the ETL load, we save them into the DB in the forward direction, so we know the previous total difficulty.

Oh good catch, one more thing, did you test it out, i am unsure whether fixCanonicalChain would work and if it did, i am pretty sure ETL collectors would be faster

**Comment by Giulio2002** [comment]
also conficts :)

**Comment by yperbasis** [comment]
> Oh good catch, one more thing, did you test it out, i am unsure whether fixCanonicalChain would work and if it did, i am pretty sure ETL collectors would be faster

No, I didn't test it out. But `fixCanonicalChain` is already used in the PoW downloader, so it should work fine. I'd like to reuse as many bits between the PoS and PoW downloaders as possible.

I wouldn't worry about performance too much right now. Let's first make it correct, then measure, then optimize bottlenecks. "Premature optimization is the root of all evil" :)

**Comment by Giulio2002** [comment]
i will test it out then, if thats not a problem though, i will disable headers verification and just run it with fixCanonicalChain, would that sound good?

**Comment by yperbasis** [comment]
> i will test it out then, if thats not a problem though, i will disable headers verification and just run it with fixCanonicalChain, would that sound good? my point with the collector is that i already tested it out so i know it works, but i am not sure about `fixCanonicalChain`.

Yes, of course, please test it out.

**Comment by Giulio2002** [comment]
In `cmd/rpcdameon/commands/engine_api.go` the call will always panic, this due to the fact that res.LatestValidHash can be nil and we are not handling that case. i have a fix, you can fix it yourself or i can submit mine, you can decide :)

**Comment by yperbasis** [comment]
> In `cmd/rpcdameon/commands/engine_api.go` the call will always panic, this due to the fact that res.LatestValidHash can be nil and we are not handling that case. i have a fix, you can fix it yourself or i can submit mine, you can decide :)

Please submit your fix. Thanks a lot for checking!

**Comment by yperbasis** [comment]
Converting to draft until PR #3158 is merged.

**Pull request merged**
