### PR TITLE
use headers in rpc health check

### PR DESCRIPTION
**Pull request by hexoscott**

### CODE REVIEW

**Comment by mandrigin** [comment]
@hexoscott can you add some unit-tests, especially in the place where you parse headers?

**Review by mandrigin — CHANGES_REQUESTED** [review]
unit-tests are needed

**Comment by hexoscott** [comment]
no problem, should have some good coverage there now and included the existing code using the request body

**Review by mandrigin — APPROVED** [review]
very good!

**Comment by mandrigin** [comment]
@hexoscott let's wait for the CI and then I will merge it

**Pull request merged**
