### PR TITLE
Binance Smart Chain support (WIP)

### PR DESCRIPTION
**Pull request by tsutsu**
This PR is our attempt to take the various go-ethereum changes made in https://github.com/binance-chain/bsc, and port them from being a patch-set made "on top of" geth, to being a patch-set made "on top of" Erigon.

This code compiles and runs, talks to the network, downloads, and executes blocks, but isn't yet 100% working — it fails sync around bsc-mainnet block 363.

We wanted to see if we could get this port finished and then kind of spring this on the community as a surprise; but we've encountered some technical challenges in translating the side-effects of BSC's reward-phase contract executions into the appropriate Erigon staged-sync phases.

As such, we'd appreciate if developers from both Erigon and @binance-chain could take a look at what we've done so far. I'm guessing that with your combined know-how, we could push this past the finish line.

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Thanks for the PR, will be reviewing. It looks like there are some conflict, but I cannot see in which files

**Comment by AskAlexSharov** [comment]
I will do more review tomorrow. 

Some info about Erigon:  
- package "log" doesn't really used now - we moved it to https://github.com/ledgerwatch/log - it's fork of original logger (before vendoring to Geth) - so, it has another License. Also it doesn't support feature "glog filter" - but it you need it - feel free to PR there. 
-  We also have repo https://github.com/ledgerwatch/erigon-lib  - which used for new code - and also has another License. So, if you need another licensee for your code - you can put it there.

About PR: 
- go.mod has some deps which not used - sqlite, goleveldb, ...
- "some technical challenges in translating the side-effects of BSC's reward-phase contract executions into the appropriate Erigon staged-sync phases." - take a look to ``core/blockchain.go:ExecuteBlockEphemerally->FinalizeBlockExecution` - it has "SysCall" concept and also using `state.SystemAddress` - I added it when implemented AuRa support (it only can sync with Sokol chain now, can't create blocks). It can call smart contracts after block execution. function ExecuteBlockEphemerally called during stage_execution.go - main place where execution of blocks happening - likely you can do all your side-effects there (not in separated stage).
- do all state side-effects on `ibs` object, then it will flushed to `batch` by `ibs.CommitBlock`. And batch will flush to db when it's full (at stage_execution.go). (We don't recommend increase --batchSize over default, because it's already too big).

**Comment by AskAlexSharov** [comment]
More info about Erigon: 
we recently dropped support of geth's txpool (in latest versions already no way to enable it), our pool is here: https://github.com/ledgerwatch/erigon-lib/tree/main/txpool - you can start diving into it from methods `pool.OnNewBlock` or `pool. AddRemoteTxs`. 
Docs of txpool: https://github.com/ledgerwatch/erigon/tree/devel/cmd/txpool
Design of txpool: https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design

**Comment by AlexeyAkhunov** [comment]
My first suggestion is to simplify PR by taking out goroutine pool and using `go`. I noticed that the PR changes `go` to usage of that pool in files completely unrelated to BSC. If we remove that, it should reduce the size of the PR (you can also open a fresh one if this is easier).

Second thing to notice is that type `types.Transaction` is an interface in Erigon, whereas it is non-interface in Geth. So we do not use `[]*types.Transaction` but instead `[]types.Transaction`.

As @AskAlexSharov noted, we do not use `core.TxPool` anymore, we should really remove that code. If changes in tx pool are required, this needs to be done in `erigon-lib`. I'd suggest piece-meal PRs though.

**Comment by tsutsu** [comment]
> go.mod has some deps which not used - sqlite, goleveldb, ...

> My first suggestion is to simplify PR by taking out goroutine pool and using go. I noticed that the PR changes go to usage of that pool in files completely unrelated to BSC.

> we do not use core.TxPool anymore

I believe these (and other inconsistencies, like the use of go-ethereum's vendored logger) aren't intended changes, but are rather artifacts of how long this branch lived and/or of the original merge process (which was started by exporting a diff between `bsc` and the commit of go-ethereum it was seemingly based on, and then applying those patches individually to Erigon); they weren't intentional, and will be removed/fixed up. I'll be extracting the necessary changes into a new commit, based on the tip of `devel`, and then force-pushing this branch to that new commit.

I pushed the branch as-is for now to begin discussion. It does compile/run/start to sync in its present state, so it can already be used to diagnose precisely where the BSC validation logic is going wrong, while we work on the code-quality issues in parallel.

**Comment by tsutsu** [comment]
> Second thing to notice is that type types.Transaction is an interface in Erigon, whereas it is non-interface in Geth. So we do not use `[]*types.Transaction` but instead `[]types.Transaction`.

Noted. I believe we hacked around this discrepancy in the most expedient way for us at the time (making Erigon use the same approach as the merged-in BSC code) to try to get the code running, so we could see whether it would work at all. We'll flip it around, pushing down the change into the relevant BSC code.

(The BSC codebase contains has quite a few spurious uses of pointers to types that are already effectively references anyway, e.g. `*[]*types.Transaction`, a pointer-to-a-slice; where the semantics don't require being able to e.g. resize the passed-in slice in a way visible to the caller, so the pointer there is pointless. It'll be a good bit of work to weed all of these out, but we'll do it, as we don't want to lower the quality of the Erigon codebase.)

**Comment by tsutsu** [comment]
> It can call smart contracts after block execution. function `ExecuteBlockEphemerally` called during `stage_execution.go` - main place where execution of blocks happening - likely you can do all your side-effects there (not in separated stage).

Yes, it seems to make sense to move logic that affects state (like BSC's token reward distribution) into this stage.

Looking further into the current state of the branch, I believe I actually misspoke; we were previously stuck on this problem, but I think we actually already made this decision as well (the latest few commits reflect this.)

Instead, the current problem is just some kind of subtle logic error in the flow of data into the reward-distribution code (which *is* executing in `parlia.Finalize`, called from `FinalizeBlockExecution`.) From a discussion with @brendan-kelly, the engineer responsible for most of this patch:

> [The logic] fails right when it tries to do reward finalization, because the txs (actual vs expected) don't match up when calling `applyTransaction` in `distributeToValidator`.

I believe by "don't match up", Brendan was referring to the validation code triggering nonce-mismatch errors. (@brendan-kelly, can you clarify? A log dump from running the code at block 363 would be helpful.)

Note that BSC interleaves "system" and "user" TXs within a block, rather than all the "system" TXs ending up at the end of the block. But the actual execution order is:

1. all the "user" TXs, in nonce order (during the tx-processing phase of block execution);

2. all the "system" TXs, in nonce order (during the finalization phase of block execution.)

I don't think we ever got to the bottom of what the nonces *should* be set to in the TXs in each of these phases — i.e. whether in `bsc` rewrites the nonces, or relies on go-ethereum `BlockProcessor.ApplyTransaction`-specific behavior re: how it updates nonces during block execution, etc. (I don't recall spotting any BSC-specific code that touches the nonce fields of the TXs.)

Probably a good next step would be for us to add some debug-logging to `bsc` (probably in `ApplyTransaction`) to show us each TX and its nonce, as it applies it during block execution+finalization. Then we can at least know what we're aiming for here.

**Comment by Giulio2002** [comment]
Perhaps @brendan-kelly and @tsutsu  should hop on our discord for a better communication, here on github, it looks quite harsh.

**Comment by brendan-kelly** [comment]
@tsutsu, All of those possibilities still hold. Here is the log dump and the commands I ran.

I compiled the Erigon integration tool to run `stage_exec` immediately:
```
$ go build -o ./build/bin/integration -gcflags=all='-N -l' -v ./cmd/integration && go build -o ./build/bin/erigon   -gcflags=all='-N -l' -v ./cmd/erigon
```

Here is me running until block 370 (although failing at 363) and the output:
```
$ ./build/bin/integration --datadir=../data/bsc-erigon --chain=bsc-mainnet stage_exec --block=370
INFO[11-19|12:57:48.556] Initialised chain configuration          config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}"
INFO[11-19|12:57:49.659] Stage                                    name=Execution progress=362
EROR[11-19|12:57:49.703] [1/18 Headers] Execution failed          block=363 hash=0xabd32259e01f7f37854c0c95ebbeaaf04c18eca5fa059747f693d350b8bc28ed error="expected tx hash 0x25fcefdf08b55e243b57d6b3be2bc0e88bc2dd076d246299d1eb97bba4a4998f, get 0x6971eb54baa66b420b6c58172bd1ff17e1119e2c11cfdc92c45eb920675c1bf6, nonce 1, to 0x0000000000000000000000000000000000001000, value 0x0, gas 9223372036854775807, gasPrice 0x0, data f340fa010000000000000000000000006488aa4d1955ee33403f8ccb1d4de5fb97c7ade2"
INFO[11-19|12:57:49.703] UnwindTo                                 block=362 bad_block_hash=0xabd32259e01f7f37854c0c95ebbeaaf04c18eca5fa059747f693d350b8bc28ed
INFO[11-19|12:57:49.703] [1/18 Headers] Completed on              block=362
INFO[11-19|12:57:49.709] database closed                          label=chaindata
```

**Comment by AskAlexSharov** [comment]
About “nonce mistmatch” please take a look at https://github.com/ledgerwatch/erigon/blob/2a08dbd3d98ad0b9a56470cc68fbfc6c9a1834c9/core/blockchain.go#L257
There is a hack for Sokol network which resetting system contract nonce - maybe you need enable this hack for your chainID.

**Comment by AskAlexSharov** [comment]
@brendan-kelly about “integration” tool. Take a look also on “integration state_stages” (it run all stages after stage.Senders) - it will execute and validate state root.

**Comment by tsutsu** [comment]
Going through this to clean it up, there are some other merge blockers that will have to be sorted out at some point:

- [ ] BSC changes `params.GasLimitBoundDivisor` — this would need to be moved to ChainConfig or somesuch
- [ ] BSC redefines `vm.PrecompiledContractsIstanbul`, not just by adding more precompiles, but also by changing the semantics of an existing precompile. Given that BSC's Istanbul does something different than Ethereum Istanbul, probably it should be considered a separate fork, with a name like `IstanbulBSC`.

**Comment by brendan-kelly** [comment]
@AskAlexSharov I've added a PR https://github.com/ledgerwatch/erigon-lib/pull/190 to erigon-lib to add the `ParliaSnapshot` table for the Parlia consensus engine that BSC uses.

**Comment by AlexeyAkhunov** [comment]
My suggestion is to create a new PR that just introduces Parlia into the codebase, so you can take out of this one. I would like to address these issues one by one and iteratively

**Comment by AlexeyAkhunov** [comment]
Then, next PR is to introduce changes in the ChainConfig and commend line options

**Comment by AlexeyAkhunov** [comment]
After those two (Parlia and ChainConfig/CLI), this PR can be cleaned up for easier further review and discussion

**Comment by brendan-kelly** [comment]
@AlexeyAkhunov here is the PR to add Parlia https://github.com/ledgerwatch/erigon/pull/3086. This contains minimal changes to still allow Erigon to compile.

**Comment by AskAlexSharov** [comment]
Hi. Who can help this guy: https://github.com/ledgerwatch/erigon/issues/3122 ?

**Comment by AlexeyAkhunov** [comment]
Closing this in favour of smaller PRs. We will also have some contributions from Ankr, they have the working version

**Pull request closed without merging**
