### PR TITLE
e35 fix misreads of GetLatest after partial pruning

### PR DESCRIPTION
**Pull request by awskii**

### CODE REVIEW

**Comment by awskii** [comment]
rely on maxTxNumInDomains is a bit broken. previously we used aggregatedStep atomic which restricted pruning of unaggregated step. now i changed it for maxtxnum in domains and periodically see root mismatch due to maxtxnum in files actually is not available yet, did not found a bug yet as well

**Review by AskAlexSharov — APPROVED** [review]
:-)

**Comment by AskAlexSharov** [comment]
@awskii I did test this branch:
- did run new Sepolia on `const HistoryV3AggregationStep = 1_562_500 / 10`
- did wait for step `~40`
- did `stage_exec --reset`
- got `block=2205523, nonce too high: address 0x272022ac41283f978C4846998542f6e73F3C2425, tx: 7 state: 6`
I think, can reproduce error only after `stage_exec --reset`

**Comment by awskii** [comment]
db always has newer value assumtption is broken (well, now it is obsolete after partial prune): GetLatest returned db value which was from `step < stepInFiles`

**Comment by awskii** [comment]
test on PruneSmallBatches yet flapping (green/red)

**Comment by awskii** [comment]
those keys with step < stepInFiles are just not yet pruned keys. In case if DB step smaller than available in files, just reading from the files.

**Comment by AskAlexSharov** [comment]
can reproduce `Scenario 2` today

**Comment by awskii** [comment]
--reset sets `toTxNum` smaller than committed txnum (while block number is correct)

**Pull request merged**
